language: minimal

services:
  - docker

script:
  - docker --version
  - docker-compose -f deploy/docker/docker-compose-build.yml build

#after_success:
  #- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  #- docker push airondev/udagram-reverseproxy:latest
 #- docker push airondev/udagram-api-feed:latest
 # - docker push airondev/udagram-api-user:latest
  #- docker push airondev/udagram-frontend:local

deploy:
  provider: script
  script: bash deploy/docker/docker_push.sh
  on:
    branch: main
